# Generated by Django 3.0.5 on 2020-06-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='period',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendanceclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.AttendanceClass'),
        ),
    ]
